# Generated by Django 4.2.5 on 2026-02-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potholes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potholes', to=settings.AUTH_USER_MODEL),
        ),
    ]
