# Generated by Django 4.2.5 on 2026-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
