# Generated by Django 4.2.5 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0002_alter_pothole_description'),
        ('potholes', '0002_alter_pothole_user'),
    ]

    operations = [
    ]
