# Generated by Django 4.2.5 on 2026-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0003_merge_20260408_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='pothole',
            index=models.Index(fields=['latitude', 'longitude'], name='potholes_po_latitud_1e5a72_idx'),
        ),
    ]
