# Generated by Django 4.2.5 on 2026-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0004_pothole_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
