# Generated by Django 4.2.5 on 2026-04-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0005_pothole_fixed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pothole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='potholes.pothole'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=10),
        ),
        migrations.AddIndex(
            model_name='pothole',
            index=models.Index(fields=['status'], name='potholes_po_status_4b9ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='pothole',
            index=models.Index(fields=['severity'], name='potholes_po_severit_d85de0_idx'),
        ),
        migrations.AddIndex(
            model_name='pothole',
            index=models.Index(fields=['is_archived'], name='potholes_po_is_arch_ed7d42_idx'),
        ),
        migrations.AddIndex(
            model_name='pothole',
            index=models.Index(fields=['created_at'], name='potholes_po_created_4e15b2_idx'),
        ),
    ]
